// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt_irqmngS_saQ_JzDX9ag3RS5uIjC9xQ',
    appId: '1:43539432786:web:35318514f1ad8b0eb1668b',
    messagingSenderId: '43539432786',
    projectId: 'notificacion-slg',
    authDomain: 'notificacion-slg.firebaseapp.com',
    storageBucket: 'notificacion-slg.appspot.com',
    measurementId: 'G-464Z1ZCRPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASfuPFWcgXayoEMBqJIQldnaaSqb-0Gtc',
    appId: '1:43539432786:android:4ef2810a3bbfb8cbb1668b',
    messagingSenderId: '43539432786',
    projectId: 'notificacion-slg',
    storageBucket: 'notificacion-slg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCChvufDF0O24ZMmgHZPNu5-XB1XbPWt1U',
    appId: '1:43539432786:ios:8f9f7aebfa994303b1668b',
    messagingSenderId: '43539432786',
    projectId: 'notificacion-slg',
    storageBucket: 'notificacion-slg.appspot.com',
    iosBundleId: 'com.example.adminClinicaFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCChvufDF0O24ZMmgHZPNu5-XB1XbPWt1U',
    appId: '1:43539432786:ios:8f9f7aebfa994303b1668b',
    messagingSenderId: '43539432786',
    projectId: 'notificacion-slg',
    storageBucket: 'notificacion-slg.appspot.com',
    iosBundleId: 'com.example.adminClinicaFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt_irqmngS_saQ_JzDX9ag3RS5uIjC9xQ',
    appId: '1:43539432786:web:e00ad340646a027db1668b',
    messagingSenderId: '43539432786',
    projectId: 'notificacion-slg',
    authDomain: 'notificacion-slg.firebaseapp.com',
    storageBucket: 'notificacion-slg.appspot.com',
    measurementId: 'G-93MHLT91FG',
  );

}